# Generated by Django 4.2.9 on 2024-01-29 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_manage', '0003_alter_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
