# Generated by Django 4.2.9 on 2024-02-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsession_name'),
        ('book_manage', '0004_book_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='chat_sessions',
            field=models.ManyToManyField(to='chat.chatsession'),
        ),
    ]
