# Generated by Django 4.2.9 on 2024-02-28 07:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book_manage', '0008_alter_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='chat_sessions',
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
