# Generated by Django 5.0.1 on 2024-01-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "session_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
