# Generated by Django 5.0.1 on 2024-01-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_chatsession_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
