# Generated by Django 4.2.9 on 2024-02-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_manage', '0009_remove_book_chat_sessions_alter_book_id'),
        ('chat', '0003_chatsession_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='linked_books',
            field=models.ManyToManyField(to='book_manage.book'),
        ),
    ]
