# Generated by Django 5.0.6 on 2024-05-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting', models.TextField()),
            ],
        ),
    ]
