# Generated by Django 5.0.6 on 2024-05-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rolesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_retrieval',
            field=models.BooleanField(default=False),
        ),
    ]
