# for local development
version: '3.7'
services:
  quasar:
    build:
      context: .
      target: 'develop-stage'
    network_mode: host
    volumes:
    - '.:/app'
    command: /bin/sh -c "yarn vite"