# develop stage
FROM node:18-alpine as develop-stage
WORKDIR /app
COPY package*.json ./
RUN yarn config set registry http://registry.npm.taobao.org/ && yarn config set registry https://registry.npmjs.org/ && yarn

# build stage
FROM develop-stage as build-stage
COPY . .
RUN yarn build

# production stage
FROM nginx:1.17.5-alpine as production-stage
COPY --from=build-stage /app/dist/ /usr/share/nginx/html/
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]