# for local development
version: '3.7'
services:
  quasar:
    build:
      context: .
      target: 'develop-stage'
    network_mode: host
    volumes:
    - '.:/app'
    command: /bin/sh -c "yarn config set registry http://registry.npm.taobao.org/ && yarn config set registry https://registry.npmjs.org/ && yarn && yarn vite"
