# Generated by Django 5.0.1 on 2024-01-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('task_id', models.CharField(max_length=100, null=True)),
                ('doccano_task_id', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
