version: "3.7"
services:
  web:
    build: 
      context: .
      target: 'python-develop-stage'
    command: /bin/sh -c "python manage.py runsslserver --certificate cert/ssl.pem --key cert/ssl.key 0.0.0.0:617"
    volumes:
      - .:/app
    restart: always
    network_mode: host
    depends_on:
      - redis
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "always", "--bind", "0.0.0.0"]
    restart: always