services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    logging:
      options:
        max-size: "200k"
        max-file: "10"
        log-path: "./logs"
    depends_on:
      - celery
  
  celery:
    build: .
    command: celery -A mysite worker -l info
    restart: always
    logging:
      options:
        max-size: "200k"
        max-file: "10"
        log-path: "./logs"
    volumes:
      - .:/app

volumes:
  extraction_volume: