services:
  web:
    build: 
      context: .
      target: 'python-develop-stage'
    command: /bin/sh -c "pip3 install -q --no-cache-dir -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - celery
  
  celery:
    build: 
      context: .
      target: 'python-develop-stage'
    command: /bin/sh -c "pip3 install -q --no-cache-dir -r requirements.txt && celery -A mysite worker -l info"
    restart: always
    network_mode: host
    volumes:
      - .:/app
    depends_on:
      - redis
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

volumes:
  extraction_volume: